name: ml_project
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - pytorch>=1.9.0
  - pip:
    - fastapi>=0.68.0
    - uvicorn>=0.15.0
    - requests>=2.26.0
    - python-dotenv>=0.19.0
    - pyyaml>=5.4.1
    - transformers>=4.11.0
    - pytest>=6.2.5
    - pytest-cov>=2.12.0
    - loguru>=0.5.3
    - black>=21.7b0
    - isort>=5.9.3
    - flake8>=3.9.2 